Ext.define('AM.store.weeklyreportstore',{
    extend:'Ext.data.Store',
    model:'AM.model.weeklyreport',
    storeId:'weeklyreportstore',
    pageSize:10,
    proxy:{
        type:'ajax',
        url:'/weeklyreport/allweeklyreports',
        reader:{
            type:'json',
            root:'data',
            totalProperty:'total'
        }
    },
    autoLoad:true
})